version: "3.11"

services:
  djangoapp:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=weather_api
      - DATABASE_USERNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOSTNAME=db
      - DATABASE_PASSWORD=admin
      - SECRET_KEY='django-insecure-h_&oz@(pv7zru@(fr76hbeo8f^6m+#-p+go7&q26yo61=ml0u@'
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=weather_api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  pgdata: